// Song database
// - videoId: YouTube video id
// - startTime/endTime: highlight segment in seconds

const KPOP_SONGS = [
  { title: "Dynamite", artist: "BTS", videoId: "gdZLi9oWNZg", startTime: 63, endTime: 76 },
  { title: "Butter", artist: "BTS", videoId: "WMweEpGlu_U", startTime: 54, endTime: 67 },
  { title: "Boy With Luv", artist: "BTS ft. Halsey", videoId: "XsX3ATc3FbA", startTime: 56, endTime: 69 },
  { title: "Spring Day", artist: "BTS", videoId: "xEeFrLSkMm8", startTime: 107, endTime: 120 },
  { title: "DNA", artist: "BTS", videoId: "MBdVXkSdhwU", startTime: 60, endTime: 73 },
  { title: "FAKE LOVE", artist: "BTS", videoId: "7C2z4GqqS5E", startTime: 57, endTime: 70 },
  { title: "Blood Sweat & Tears", artist: "BTS", videoId: "hmE9f-TEutc", startTime: 53, endTime: 66 },
  { title: "DDU-DU DDU-DU", artist: "BLACKPINK", videoId: "IHNzOHi8sJs", startTime: 56, endTime: 69 },
  { title: "How You Like That", artist: "BLACKPINK", videoId: "ioNng23DkIM", startTime: 68, endTime: 81 },
  { title: "Pink Venom", artist: "BLACKPINK", videoId: "gQlMMD8auMs", startTime: 53, endTime: 66 },
  { title: "Lovesick Girls", artist: "BLACKPINK", videoId: "dyRsYk0LyA8", startTime: 56, endTime: 69 },
  { title: "Kill This Love", artist: "BLACKPINK", videoId: "2S24-y0Ij3Y", startTime: 52, endTime: 65 },
  { title: "BOOMBAYAH", artist: "BLACKPINK", videoId: "bwmSjveL3Lc", startTime: 52, endTime: 65 },
  { title: "Whistle", artist: "BLACKPINK", videoId: "dISNgvVpWlo", startTime: 51, endTime: 64 },
  { title: "Hype Boy", artist: "NewJeans", videoId: "11cta61wi0g", startTime: 53, endTime: 66 },
  { title: "Ditto", artist: "NewJeans", videoId: "pSUydWEqKwE", startTime: 60, endTime: 73 },
  { title: "Super Shy", artist: "NewJeans", videoId: "ArmDp-zijuc", startTime: 51, endTime: 64 },
  { title: "OMG", artist: "NewJeans", videoId: "sVTy_wmn5SU", startTime: 58, endTime: 71 },
  { title: "Attention", artist: "NewJeans", videoId: "js1CtxSY38I", startTime: 54, endTime: 67 },
  { title: "ETA", artist: "NewJeans", videoId: "jOTfBlKSQYY", startTime: 41, endTime: 54 },
  { title: "Next Level", artist: "aespa", videoId: "4TWR90KJl84", startTime: 95, endTime: 108 },
  { title: "Supernova", artist: "aespa", videoId: "phuiiNCxRMg", startTime: 60, endTime: 73 },
  { title: "Savage", artist: "aespa", videoId: "WPdWvnAAurg", startTime: 57, endTime: 70 },
  { title: "Drama", artist: "aespa", videoId: "dHKfnHRMaKE", startTime: 60, endTime: 73 },
  { title: "Love Dive", artist: "IVE", videoId: "Y8JFxS1HlDo", startTime: 59, endTime: 72 },
  { title: "ELEVEN", artist: "IVE", videoId: "NKhSfAJiVYk", startTime: 61, endTime: 74 },
  { title: "After LIKE", artist: "IVE", videoId: "F0B7HDiY-10", startTime: 57, endTime: 70 },
  { title: "Kitsch", artist: "IVE", videoId: "Cnfn5nOHMdQ", startTime: 50, endTime: 63 },
  { title: "ANTIFRAGILE", artist: "LE SSERAFIM", videoId: "pyf8cbqyfPs", startTime: 58, endTime: 71 },
  { title: "FEARLESS", artist: "LE SSERAFIM", videoId: "4vbDFu0PUew", startTime: 55, endTime: 68 },
  { title: "Perfect Night", artist: "LE SSERAFIM", videoId: "hLvhYdi5V9Y", startTime: 50, endTime: 63 },
  { title: "Cheer Up", artist: "TWICE", videoId: "c7rCyll5AeY", startTime: 55, endTime: 68 },
  { title: "TT", artist: "TWICE", videoId: "ePpPVE-GGJw", startTime: 60, endTime: 73 },
  { title: "LIKEY", artist: "TWICE", videoId: "V2hlQkVJZhE", startTime: 51, endTime: 64 },
  { title: "What is Love?", artist: "TWICE", videoId: "i0p1bmr0EmE", startTime: 55, endTime: 68 },
  { title: "Feel Special", artist: "TWICE", videoId: "3ymwOvzhwHs", startTime: 63, endTime: 76 },
  { title: "Feel My Rhythm", artist: "Red Velvet", videoId: "R9At2ICm4LQ", startTime: 63, endTime: 76 },
  { title: "Psycho", artist: "Red Velvet", videoId: "uR8Mrt1IpXg", startTime: 58, endTime: 71 },
  { title: "Red Flavor", artist: "Red Velvet", videoId: "WyiIGEHQP8o", startTime: 49, endTime: 62 },
  { title: "Bad Boy", artist: "Red Velvet", videoId: "J_CFBjAyPWE", startTime: 53, endTime: 66 },
  { title: "TOMBOY", artist: "(G)I-DLE", videoId: "Jh4QFaPmdss", startTime: 49, endTime: 62 },
  { title: "Queencard", artist: "(G)I-DLE", videoId: "7BkBymSsb7o", startTime: 58, endTime: 71 },
  { title: "Love Shot", artist: "EXO", videoId: "pSudEWAYvVU", startTime: 67, endTime: 80 },
  { title: "Growl", artist: "EXO", videoId: "I3dezFzsNss", startTime: 48, endTime: 61 },
  { title: "God's Menu", artist: "Stray Kids", videoId: "TQTlCHxyuu8", startTime: 47, endTime: 60 },
  { title: "S-Class", artist: "Stray Kids", videoId: "p95Ql2SEfg4", startTime: 43, endTime: 56 },
  { title: "Super", artist: "SEVENTEEN", videoId: "x-GM1NG1Mhk", startTime: 57, endTime: 70 },
  { title: "Very Nice", artist: "SEVENTEEN", videoId: "J-wFp43XOrA", startTime: 53, endTime: 66 },
  { title: "Gangnam Style", artist: "PSY", videoId: "9bZkp7q19f0", startTime: 44, endTime: 57 },
  { title: "Fantastic Baby", artist: "BIGBANG", videoId: "AAbokV76tkU", startTime: 58, endTime: 71 },
];

const POP_SONGS = [
  { title: "Shape of You", artist: "Ed Sheeran", videoId: "JGwWNGJdvx8", startTime: 46, endTime: 59 },
  { title: "Perfect", artist: "Ed Sheeran", videoId: "2Vv-BfVoq4g", startTime: 72, endTime: 85 },
  { title: "Thinking Out Loud", artist: "Ed Sheeran", videoId: "lp-EO5I60KA", startTime: 58, endTime: 71 },
  { title: "Blinding Lights", artist: "The Weeknd", videoId: "4NRXx6U8ABQ", startTime: 53, endTime: 66 },
  { title: "Starboy", artist: "The Weeknd ft. Daft Punk", videoId: "34Na4j8AVgA", startTime: 47, endTime: 60 },
  { title: "Save Your Tears", artist: "The Weeknd", videoId: "XXYlFuWEuKI", startTime: 59, endTime: 72 },
  { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", videoId: "OPf0YbXqDm0", startTime: 59, endTime: 72 },
  { title: "Just the Way You Are", artist: "Bruno Mars", videoId: "LjhCEhWiKXk", startTime: 60, endTime: 73 },
  { title: "24K Magic", artist: "Bruno Mars", videoId: "UqyT8IEBkvY", startTime: 51, endTime: 64 },
  { title: "Rolling in the Deep", artist: "Adele", videoId: "rYEDA3JcQqw", startTime: 62, endTime: 75 },
  { title: "Someone Like You", artist: "Adele", videoId: "hLQl3WQQoQ0", startTime: 63, endTime: 76 },
  { title: "Hello", artist: "Adele", videoId: "YQHsXMglC9A", startTime: 73, endTime: 86 },
  { title: "Shake It Off", artist: "Taylor Swift", videoId: "nfWlot6h_JM", startTime: 58, endTime: 71 },
  { title: "Anti-Hero", artist: "Taylor Swift", videoId: "b1kbLwvqugk", startTime: 55, endTime: 68 },
  { title: "Blank Space", artist: "Taylor Swift", videoId: "e-ORhEE9VVg", startTime: 58, endTime: 71 },
  { title: "Love Story", artist: "Taylor Swift", videoId: "8xg3vE8Ie_E", startTime: 68, endTime: 81 },
  { title: "bad guy", artist: "Billie Eilish", videoId: "DyDfgMOUjCI", startTime: 51, endTime: 64 },
  { title: "lovely", artist: "Billie Eilish & Khalid", videoId: "V1Pl8CzNzCw", startTime: 55, endTime: 68 },
  { title: "Bohemian Rhapsody", artist: "Queen", videoId: "fJ9rUzIMcZQ", startTime: 128, endTime: 141 },
  { title: "Don't Stop Me Now", artist: "Queen", videoId: "HgzGwKwLmgM", startTime: 50, endTime: 63 },
  { title: "We Will Rock You", artist: "Queen", videoId: "-tJYN-eG1zk", startTime: 27, endTime: 40 },
  { title: "Billie Jean", artist: "Michael Jackson", videoId: "Zi_XLOBDo_Y", startTime: 53, endTime: 66 },
  { title: "Beat It", artist: "Michael Jackson", videoId: "oRdxUFDoQe0", startTime: 62, endTime: 75 },
  { title: "Thriller", artist: "Michael Jackson", videoId: "sOnqjkJTMaA", startTime: 63, endTime: 76 },
  { title: "As It Was", artist: "Harry Styles", videoId: "H5v3kku4y6Q", startTime: 53, endTime: 66 },
  { title: "Watermelon Sugar", artist: "Harry Styles", videoId: "E07s5ZYadZA", startTime: 52, endTime: 65 },
  { title: "Levitating", artist: "Dua Lipa", videoId: "TUVcZfQe-Kw", startTime: 49, endTime: 62 },
  { title: "Don't Start Now", artist: "Dua Lipa", videoId: "oygrmJFKYZY", startTime: 49, endTime: 62 },
  { title: "New Rules", artist: "Dua Lipa", videoId: "k2qgadSvNyU", startTime: 51, endTime: 64 },
  { title: "Sugar", artist: "Maroon 5", videoId: "09R8_2nJtjg", startTime: 54, endTime: 67 },
  { title: "Memories", artist: "Maroon 5", videoId: "SlPhMPnQ58k", startTime: 45, endTime: 58 },
  { title: "Payphone", artist: "Maroon 5", videoId: "KRaWnd3LJfs", startTime: 63, endTime: 76 },
  { title: "STAY", artist: "The Kid LAROI & Justin Bieber", videoId: "kTJczUoc26U", startTime: 28, endTime: 41 },
  { title: "Peaches", artist: "Justin Bieber", videoId: "tQ0yjYUFKAE", startTime: 49, endTime: 62 },
  { title: "Baby", artist: "Justin Bieber ft. Ludacris", videoId: "kffacxfA7G4", startTime: 33, endTime: 46 },
  { title: "Sorry", artist: "Justin Bieber", videoId: "fRh_vgS2dFE", startTime: 37, endTime: 50 },
  { title: "Bad Romance", artist: "Lady Gaga", videoId: "qrO4YZeyl0I", startTime: 53, endTime: 66 },
  { title: "Poker Face", artist: "Lady Gaga", videoId: "bESGLojNYSo", startTime: 56, endTime: 69 },
  { title: "Believer", artist: "Imagine Dragons", videoId: "7wtfhZwyrcc", startTime: 60, endTime: 73 },
  { title: "Radioactive", artist: "Imagine Dragons", videoId: "ktvTqknDobU", startTime: 62, endTime: 75 },
  { title: "Thunder", artist: "Imagine Dragons", videoId: "fKopy74weus", startTime: 42, endTime: 55 },
  { title: "Viva la Vida", artist: "Coldplay", videoId: "dvgZkm1xWPE", startTime: 60, endTime: 73 },
  { title: "Fix You", artist: "Coldplay", videoId: "k4V3Mo61fJM", startTime: 230, endTime: 243 },
  { title: "Yellow", artist: "Coldplay", videoId: "yKNxeF4KMsY", startTime: 55, endTime: 68 },
  { title: "Despacito", artist: "Luis Fonsi ft. Daddy Yankee", videoId: "kJQP7kiw5Fk", startTime: 57, endTime: 70 },
  { title: "Dance Monkey", artist: "Tones and I", videoId: "q0hyYWKXF0Q", startTime: 37, endTime: 50 },
  { title: "Old Town Road", artist: "Lil Nas X", videoId: "r7qovpFAGrQ", startTime: 32, endTime: 45 },
  { title: "See You Again", artist: "Wiz Khalifa ft. Charlie Puth", videoId: "RgKAFK5djSk", startTime: 55, endTime: 68 },
  { title: "Counting Stars", artist: "OneRepublic", videoId: "hT_nvWreIhg", startTime: 63, endTime: 76 },
  { title: "Closer", artist: "The Chainsmokers ft. Halsey", videoId: "PT2_F-1esPk", startTime: 65, endTime: 78 },
];

const SONGS_DB = [...KPOP_SONGS, ...POP_SONGS];

if (POP_SONGS.length !== 50) {
  console.warn(`POP_SONGS length is ${POP_SONGS.length}. Expected 50.`);
}
