// Korean/K-pop focused song database (200 tracks)
// videoId: YouTube video id
// startTime/endTime: base highlight window in seconds
// app.js applies global clip tuning (50% length, +8s start shift)

const SONGS_DB = [
  { title: "Dynamite", artist: "방탄소년단", videoId: "gdZLi9oWNZg", startTime: 42, endTime: 55 },
  { title: "Butter", artist: "방탄소년단", videoId: "WMweEpGlu_U", startTime: 45, endTime: 58 },
  { title: "작은 것들을 위한 시", artist: "방탄소년단", videoId: "XsX3ATc3FbA", startTime: 48, endTime: 61 },
  { title: "봄날", artist: "방탄소년단", videoId: "xEeFrLSkMm8", startTime: 51, endTime: 64 },
  { title: "DNA", artist: "방탄소년단", videoId: "MBdVXkSdhwU", startTime: 54, endTime: 67 },
  { title: "FAKE LOVE", artist: "방탄소년단", videoId: "7C2z4GqqS5E", startTime: 57, endTime: 70 },
  { title: "IDOL", artist: "방탄소년단", videoId: "pBuZEGYXA6E", startTime: 60, endTime: 73 },
  { title: "ON", artist: "방탄소년단", videoId: "gwMa6gpoE9I", startTime: 63, endTime: 76 },
  { title: "불타오르네", artist: "방탄소년단", videoId: "4ujQOR2DMFM", startTime: 42, endTime: 55 },
  { title: "Permission to Dance", artist: "방탄소년단", videoId: "CuklIb9d3fI", startTime: 60, endTime: 73 },
  { title: "DDU-DU DDU-DU", artist: "블랙핑크", videoId: "IHNzOHi8sJs", startTime: 63, endTime: 76 },
  { title: "How You Like That", artist: "블랙핑크", videoId: "ioNng23DkIM", startTime: 42, endTime: 55 },
  { title: "Pink Venom", artist: "블랙핑크", videoId: "gQlMMD8auMs", startTime: 45, endTime: 58 },
  { title: "Kill This Love", artist: "블랙핑크", videoId: "2S24-y0Ij3Y", startTime: 48, endTime: 61 },
  { title: "Lovesick Girls", artist: "블랙핑크", videoId: "dyRsYk0LyA8", startTime: 51, endTime: 64 },
  { title: "BOOMBAYAH", artist: "블랙핑크", videoId: "bwmSjveL3Lc", startTime: 54, endTime: 67 },
  { title: "휘파람", artist: "블랙핑크", videoId: "dISNgvVpWlo", startTime: 57, endTime: 70 },
  { title: "마지막처럼", artist: "블랙핑크", videoId: "Amq-qlqbjYA", startTime: 60, endTime: 73 },
  { title: "불장난", artist: "블랙핑크", videoId: "9pdj4iJD08s", startTime: 63, endTime: 76 },
  { title: "Cheer Up", artist: "트와이스", videoId: "c7rCyll5AeY", startTime: 45, endTime: 58 },
  { title: "TT", artist: "트와이스", videoId: "ePpPVE-GGJw", startTime: 48, endTime: 61 },
  { title: "LIKEY", artist: "트와이스", videoId: "V2hlQkVJZhE", startTime: 51, endTime: 64 },
  { title: "What is Love?", artist: "트와이스", videoId: "i0p1bmr0EmE", startTime: 54, endTime: 67 },
  { title: "Feel Special", artist: "트와이스", videoId: "3ymwOvzhwHs", startTime: 57, endTime: 70 },
  { title: "FANCY", artist: "트와이스", videoId: "kOHB85vDuow", startTime: 60, endTime: 73 },
  { title: "YES or YES", artist: "트와이스", videoId: "mAKsZ26SabQ", startTime: 63, endTime: 76 },
  { title: "Dance The Night Away", artist: "트와이스", videoId: "Fm5iP0S1z9w", startTime: 42, endTime: 55 },
  { title: "MORE & MORE", artist: "트와이스", videoId: "mH0_XpSHkZo", startTime: 57, endTime: 70 },
  { title: "Heart Shaker", artist: "트와이스", videoId: "rRzxEiBLQCA", startTime: 60, endTime: 73 },
  { title: "SIGNAL", artist: "트와이스", videoId: "VQtonf1fv_s", startTime: 63, endTime: 76 },
  { title: "Attention", artist: "뉴진스", videoId: "js1CtxSY38I", startTime: 42, endTime: 55 },
  { title: "Hype Boy", artist: "뉴진스", videoId: "9wUKhEgnllc", startTime: 45, endTime: 58 },
  { title: "Ditto", artist: "뉴진스", videoId: "pSUydWEqKwE", startTime: 48, endTime: 61 },
  { title: "OMG", artist: "뉴진스", videoId: "_ZAgIHmHLdc", startTime: 51, endTime: 64 },
  { title: "Super Shy", artist: "뉴진스", videoId: "ArmDp-zijuc", startTime: 54, endTime: 67 },
  { title: "ETA", artist: "뉴진스", videoId: "jOTfBlKSQYY", startTime: 57, endTime: 70 },
  { title: "Cookie", artist: "뉴진스", videoId: "VOmIplFAGeg", startTime: 60, endTime: 73 },
  { title: "ASAP", artist: "뉴진스", videoId: "dJdqn5v4Dkw", startTime: 63, endTime: 76 },
  { title: "How Sweet", artist: "뉴진스", videoId: "Q3K0TOvTOno", startTime: 42, endTime: 55 },
  { title: "Black Mamba", artist: "에스파", videoId: "ZeerrnuLi5E", startTime: 48, endTime: 61 },
  { title: "Next Level", artist: "에스파", videoId: "4TWR90KJl84", startTime: 51, endTime: 64 },
  { title: "Savage", artist: "에스파", videoId: "WPdWvnAAurg", startTime: 54, endTime: 67 },
  { title: "Girls", artist: "에스파", videoId: "dYRITmpFbJ4", startTime: 57, endTime: 70 },
  { title: "Spicy", artist: "에스파", videoId: "Os_heh8vPfs", startTime: 60, endTime: 73 },
  { title: "Drama", artist: "에스파", videoId: "D8VEhcPeSlc", startTime: 63, endTime: 76 },
  { title: "Supernova", artist: "에스파", videoId: "phuiiNCxRMg", startTime: 42, endTime: 55 },
  { title: "Armageddon", artist: "에스파", videoId: "nFYwcndNuOY", startTime: 45, endTime: 58 },
  { title: "ELEVEN", artist: "아이브", videoId: "--FmExEAsM8", startTime: 48, endTime: 61 },
  { title: "LOVE DIVE", artist: "아이브", videoId: "Y8JFxS1HlDo", startTime: 51, endTime: 64 },
  { title: "After LIKE", artist: "아이브", videoId: "F0B7HDiY-10", startTime: 54, endTime: 67 },
  { title: "Kitsch", artist: "아이브", videoId: "pG6iaOMV46I", startTime: 57, endTime: 70 },
  { title: "I AM", artist: "아이브", videoId: "6ZUIwj3FgUY", startTime: 60, endTime: 73 },
  { title: "Baddie", artist: "아이브", videoId: "Da4P2uT4mVc", startTime: 63, endTime: 76 },
  { title: "FEARLESS", artist: "르세라핌", videoId: "4vbDFu0PUew", startTime: 45, endTime: 58 },
  { title: "ANTIFRAGILE", artist: "르세라핌", videoId: "pyf8cbqyfPs", startTime: 48, endTime: 61 },
  { title: "UNFORGIVEN", artist: "르세라핌", videoId: "UBURTj20HXI", startTime: 51, endTime: 64 },
  { title: "Smart", artist: "르세라핌", videoId: "KNexS61fjus", startTime: 60, endTime: 73 },
  { title: "TOMBOY", artist: "(여자)아이들", videoId: "Jh4QFaPmdss", startTime: 42, endTime: 55 },
  { title: "Nxde", artist: "(여자)아이들", videoId: "fCO7f0SmrDc", startTime: 45, endTime: 58 },
  { title: "Queencard", artist: "(여자)아이들", videoId: "7HDeem-JaSY", startTime: 48, endTime: 61 },
  { title: "달라달라", artist: "있지", videoId: "pNfTK39k55U", startTime: 63, endTime: 76 },
  { title: "SNEAKERS", artist: "있지", videoId: "Hbb5GPxXF1w", startTime: 54, endTime: 67 },
  { title: "CAKE", artist: "있지", videoId: "0bIRwBpBcZQ", startTime: 57, endTime: 70 },
  { title: "손오공", artist: "세븐틴", videoId: "-GQg25oP0S4", startTime: 63, endTime: 76 },
  { title: "아주 NICE", artist: "세븐틴", videoId: "J-wFp43XOrA", startTime: 45, endTime: 58 },
  { title: "으르렁", artist: "엑소", videoId: "I3dezFzsNss", startTime: 63, endTime: 76 },
  { title: "Love Shot", artist: "엑소", videoId: "pSudEWBAYRE", startTime: 42, endTime: 55 },
  { title: "Monster", artist: "엑소", videoId: "KSH-FVVtTf0", startTime: 45, endTime: 58 },
  { title: "중독", artist: "엑소", videoId: "TI0DGvqKZTI", startTime: 60, endTime: 73 },
  { title: "Psycho", artist: "레드벨벳", videoId: "uR8Mrt1IpXg", startTime: 63, endTime: 76 },
  { title: "빨간 맛", artist: "레드벨벳", videoId: "WyiIGEHQP8o", startTime: 45, endTime: 58 },
  { title: "Russian Roulette", artist: "레드벨벳", videoId: "QslJYDX3o8s", startTime: 51, endTime: 64 },
  { title: "Peek-A-Boo", artist: "레드벨벳", videoId: "6uJf2IT2Zh8", startTime: 54, endTime: 67 },
  { title: "Dumb Dumb", artist: "레드벨벳", videoId: "XGdbaEDVWp0", startTime: 57, endTime: 70 },
  { title: "Rookie", artist: "레드벨벳", videoId: "J0h8-OTC38I", startTime: 63, endTime: 76 },
  { title: "Ring Ding Dong", artist: "샤이니", videoId: "roughtzsCDI", startTime: 45, endTime: 58 },
  { title: "누난 너무 예뻐", artist: "샤이니", videoId: "VTASffPQGhY", startTime: 48, endTime: 61 },
  { title: "Gee", artist: "소녀시대", videoId: "U7mPqycQ0tQ", startTime: 60, endTime: 73 },
  { title: "다시 만난 세계", artist: "소녀시대", videoId: "0k2Zzkw_-0I", startTime: 63, endTime: 76 },
  { title: "Lion Heart", artist: "소녀시대", videoId: "nVCubhQ454c", startTime: 48, endTime: 61 },
  { title: "PARTY", artist: "소녀시대", videoId: "HQzu7NYlZNQ", startTime: 51, endTime: 64 },
  { title: "Mr.Mr.", artist: "소녀시대", videoId: "Z8j_XEn9b_8", startTime: 54, endTime: 67 },
  { title: "BANG BANG BANG", artist: "빅뱅", videoId: "2ips2mM7Zqw", startTime: 57, endTime: 70 },
  { title: "FANTASTIC BABY", artist: "빅뱅", videoId: "AAbokV76tkU", startTime: 60, endTime: 73 },
  { title: "LOSER", artist: "빅뱅", videoId: "1CTced9CMMk", startTime: 42, endTime: 55 },
  { title: "우리 사랑하지 말아요", artist: "빅뱅", videoId: "9jTo6hTZmiQ", startTime: 48, endTime: 61 },
  { title: "내가 제일 잘 나가", artist: "투애니원", videoId: "j7_lSP8Vc3o", startTime: 51, endTime: 64 },
  { title: "FIRE", artist: "투애니원", videoId: "49AfuuRbgGo", startTime: 54, endTime: 67 },
  { title: "COME BACK HOME", artist: "투애니원", videoId: "vLbfv-AAyvQ", startTime: 57, endTime: 70 },
  { title: "LONELY", artist: "투애니원", videoId: "5n4V3lGEyG4", startTime: 60, endTime: 73 },
  { title: "강남스타일", artist: "싸이", videoId: "9bZkp7q19f0", startTime: 63, endTime: 76 },
  { title: "젠틀맨", artist: "싸이", videoId: "ASO_zypdnsQ", startTime: 42, endTime: 55 },
  { title: "뉴페이스", artist: "싸이", videoId: "OwJPPaEyqhI", startTime: 45, endTime: 58 },
  { title: "대디", artist: "싸이", videoId: "FrG4TEcSuRg", startTime: 48, endTime: 61 },
  { title: "댓댓", artist: "싸이", videoId: "8dJyRm2jJ-U", startTime: 51, endTime: 64 },
  { title: "Celebrity", artist: "아이유", videoId: "0-q1KafFCLU", startTime: 54, endTime: 67 },
  { title: "Blueming", artist: "아이유", videoId: "D1PvIWdJ8xo", startTime: 57, endTime: 70 },
  { title: "팔레트", artist: "아이유", videoId: "d9IxdwEFk1c", startTime: 60, endTime: 73 },
  { title: "밤편지", artist: "아이유", videoId: "BzYnNdJhZQw", startTime: 63, endTime: 76 },
  { title: "LILAC", artist: "아이유", videoId: "v7bnOxV4jAc", startTime: 42, endTime: 55 },
  { title: "eight", artist: "아이유", videoId: "TgOu00Mf3kI", startTime: 45, endTime: 58 },
  { title: "좋은 날", artist: "아이유", videoId: "jeqdYqsrsA0", startTime: 48, endTime: 61 },
  { title: "200%", artist: "악뮤", videoId: "0Oi8jDMvd_w", startTime: 51, endTime: 64 },
  { title: "Give Love", artist: "악뮤", videoId: "x2XX3cNW4K0", startTime: 54, endTime: 67 },
  { title: "Dinosaur", artist: "악뮤", videoId: "8Oz7DG76ibY", startTime: 57, endTime: 70 },
  { title: "오랜 날 오랜 밤", artist: "악뮤", videoId: "wEQpfil0IYA", startTime: 60, endTime: 73 },
  { title: "어떻게 이별까지 사랑하겠어, 널 사랑하는 거지", artist: "악뮤", videoId: "m3DZsBw5bnE", startTime: 63, endTime: 76 },
  { title: "아무노래", artist: "지코", videoId: "UuV2BmJ1p_I", startTime: 42, endTime: 55 },
  { title: "SPOT!", artist: "지코", videoId: "xfqBQ2XhBCg", startTime: 45, endTime: 58 },
  { title: "Artist", artist: "지코", videoId: "DNPs2qqdhN0", startTime: 48, endTime: 61 },
  { title: "여행", artist: "볼빨간사춘기", videoId: "xRbPAVnqtcs", startTime: 51, endTime: 64 },
  { title: "썸 탈꺼야", artist: "볼빨간사춘기", videoId: "hZmoMyFXDoI", startTime: 54, endTime: 67 },
  { title: "벚꽃 엔딩", artist: "버스커버스커", videoId: "tXV7dfvSefo", startTime: 57, endTime: 70 },
  { title: "롤린", artist: "브레이브걸스", videoId: "-Axm4IYHVYk", startTime: 60, endTime: 73 },
  { title: "롤리폴리", artist: "티아라", videoId: "afwK0Mv0IsY", startTime: 63, endTime: 76 },
  { title: "Nobody", artist: "원더걸스", videoId: "QZBn1e9pr2Q", startTime: 51, endTime: 64 },
  { title: "Tell Me", artist: "원더걸스", videoId: "BlHv3BbBv6A", startTime: 54, endTime: 67 },
  { title: "So Hot", artist: "원더걸스", videoId: "lmun5PO54VE", startTime: 57, endTime: 70 },
  { title: "Touch My Body", artist: "씨스타", videoId: "9txzvu6eQuw", startTime: 60, endTime: 73 },
  { title: "Shake It", artist: "씨스타", videoId: "x9-TIy7WPQI", startTime: 63, endTime: 76 },
  { title: "NoNoNo", artist: "에이핑크", videoId: "hspqQuuuGIw", startTime: 42, endTime: 55 },
  { title: "Mr. Chu", artist: "에이핑크", videoId: "K5H-GvnNz2Y", startTime: 45, endTime: 58 },
  { title: "LUV", artist: "에이핑크", videoId: "8dVjSvLzD1I", startTime: 48, endTime: 61 },
  { title: "오늘부터 우리는", artist: "여자친구", videoId: "YYHyAIFG3iI", startTime: 51, endTime: 64 },
  { title: "시간을 달려서", artist: "여자친구", videoId: "r_6q_-d-7Sk", startTime: 54, endTime: 67 },
  { title: "너 그리고 나", artist: "여자친구", videoId: "1ZhDsPdvl6c", startTime: 57, endTime: 70 },
  { title: "HIP", artist: "마마무", videoId: "KhTeiaCezwM", startTime: 60, endTime: 73 },
  { title: "별이 빛나는 밤", artist: "마마무", videoId: "LjUXm0Zy_dk", startTime: 63, endTime: 76 },
  { title: "Shake It Off", artist: "Taylor Swift", videoId: "nfWlot6h_JM", startTime: 42, endTime: 55 },
  { title: "Blank Space", artist: "Taylor Swift", videoId: "e-ORhEE9VVg", startTime: 45, endTime: 58 },
  { title: "Love Story", artist: "Taylor Swift", videoId: "8xg3vE8Ie_E", startTime: 48, endTime: 61 },
  { title: "Uptown Funk", artist: "Bruno Mars", videoId: "OPf0YbXqDm0", startTime: 42, endTime: 55 },
  { title: "Sorry", artist: "Justin Bieber", videoId: "fRh_vgS2dFE", startTime: 42, endTime: 55 },
  { title: "Love Yourself", artist: "Justin Bieber", videoId: "oyEuk8j8imI", startTime: 45, endTime: 58 },
  { title: "What Do You Mean?", artist: "Justin Bieber", videoId: "DK_0jXPuIr0", startTime: 48, endTime: 61 },
  { title: "Baby", artist: "Justin Bieber", videoId: "kffacxfA7G4", startTime: 51, endTime: 64 },
  { title: "bad guy", artist: "Billie Eilish", videoId: "DyDfgMOUjCI", startTime: 42, endTime: 55 },
  { title: "everything i wanted", artist: "Billie Eilish", videoId: "EgBJmlPo8Xw", startTime: 45, endTime: 58 },
  { title: "Don't Start Now", artist: "Dua Lipa", videoId: "oygrmJFKYZY", startTime: 45, endTime: 58 },
  { title: "Levitating", artist: "Dua Lipa", videoId: "TUVcZfQe-Kw", startTime: 48, endTime: 61 },
  { title: "Blinding Lights", artist: "The Weeknd", videoId: "4NRXx6U8ABQ", startTime: 42, endTime: 55 },
  { title: "Save Your Tears", artist: "The Weeknd", videoId: "XXYlFuWEuKI", startTime: 45, endTime: 58 },
  { title: "Starboy", artist: "The Weeknd", videoId: "34Na4j8AVgA", startTime: 48, endTime: 61 },
  { title: "Can't Feel My Face", artist: "The Weeknd", videoId: "KEI4qSrkPAs", startTime: 51, endTime: 64 },
  { title: "Shape of You", artist: "Ed Sheeran", videoId: "JGwWNGJdvx8", startTime: 42, endTime: 55 },
  { title: "Perfect", artist: "Ed Sheeran", videoId: "2Vv-BfVoq4g", startTime: 45, endTime: 58 },
  { title: "Photograph", artist: "Ed Sheeran", videoId: "nSDgHBxUbVQ", startTime: 51, endTime: 64 },
  { title: "Roar", artist: "Katy Perry", videoId: "CevxZvSJLk8", startTime: 42, endTime: 55 },
  { title: "Firework", artist: "Katy Perry", videoId: "QGJuMBdaqIw", startTime: 48, endTime: 61 },
  { title: "Hello", artist: "Adele", videoId: "YQHsXMglC9A", startTime: 42, endTime: 55 },
  { title: "Rolling in the Deep", artist: "Adele", videoId: "rYEDA3JcQqw", startTime: 45, endTime: 58 },
  { title: "Sugar", artist: "Maroon 5", videoId: "09R8_2nJtjg", startTime: 42, endTime: 55 },
  { title: "Girls Like You", artist: "Maroon 5", videoId: "aJOTlE1K90k", startTime: 45, endTime: 58 },
  { title: "Moves Like Jagger", artist: "Maroon 5", videoId: "suRsxpoAc5w", startTime: 48, endTime: 61 },
  { title: "Payphone", artist: "Maroon 5", videoId: "KRaWnd3LJfs", startTime: 51, endTime: 64 },
  { title: "What Makes You Beautiful", artist: "One Direction", videoId: "QJO3ROT-A4E", startTime: 42, endTime: 55 },
  { title: "Story of My Life", artist: "One Direction", videoId: "W-TE_Ys4iwM", startTime: 45, endTime: 58 },
  { title: "Drag Me Down", artist: "One Direction", videoId: "Jwgf3wmiA04", startTime: 48, endTime: 61 },
  { title: "라잇 나우", artist: "싸이", videoId: "UmHdefsaL6I", startTime: 51, endTime: 64 },
  { title: "행오버", artist: "싸이", videoId: "HkMNOlYcpHg", startTime: 54, endTime: 67 },
  { title: "아이 러브 잇", artist: "싸이", videoId: "Xvjnoagk6GU", startTime: 57, endTime: 70 },
  { title: "나팔바지", artist: "싸이", videoId: "tF27TNC_4pc", startTime: 60, endTime: 73 },
  { title: "셀럽", artist: "싸이", videoId: "vgc_Y_3bSj4", startTime: 63, endTime: 76 },
  { title: "챔피언", artist: "싸이", videoId: "DglxQVJX3Mo", startTime: 42, endTime: 55 },
  { title: "형", artist: "노라조", videoId: "aGvTFU7NP8I", startTime: 45, endTime: 58 },
  { title: "빵", artist: "노라조", videoId: "iCPVbxBcQ1k", startTime: 48, endTime: 61 },
  { title: "슈퍼맨", artist: "노라조", videoId: "Nq0bKUjtCe8", startTime: 51, endTime: 64 },
  { title: "Stitches", artist: "Shawn Mendes", videoId: "VbfpW0pbvaU", startTime: 54, endTime: 67 },
  { title: "Treat You Better", artist: "Shawn Mendes", videoId: "lY2yjAdbvdQ", startTime: 57, endTime: 70 },
  { title: "There's Nothing Holdin' Me Back", artist: "Shawn Mendes", videoId: "dT2owtxkU8k", startTime: 60, endTime: 73 },
  { title: "Mercy", artist: "Shawn Mendes", videoId: "KkGVmN68ByU", startTime: 63, endTime: 76 },
  { title: "In My Blood", artist: "Shawn Mendes", videoId: "36tggrpRoTI", startTime: 42, endTime: 55 },
  { title: "If I Can't Have You", artist: "Shawn Mendes", videoId: "oTJ-oqwxdZY", startTime: 45, endTime: 58 },
  { title: "Senorita", artist: "Shawn Mendes", videoId: "Pkh8UtuejGw", startTime: 48, endTime: 61 },
  { title: "Wonder", artist: "Shawn Mendes", videoId: "sQYxmpuyxG8", startTime: 51, endTime: 64 },
  { title: "Stan", artist: "Eminem", videoId: "gOMhN-hfMtY", startTime: 54, endTime: 67 },
  { title: "Lost in Japan", artist: "Shawn Mendes", videoId: "ycy30LIbq4w", startTime: 57, endTime: 70 },
  { title: "Lose Yourself", artist: "Eminem", videoId: "xFYQQPAOz7Y", startTime: 60, endTime: 73 },
  { title: "Without Me", artist: "Eminem", videoId: "YVkUvmDQ3HY", startTime: 63, endTime: 76 },
  { title: "Love The Way You Lie", artist: "Eminem", videoId: "uelHwf8o7_U", startTime: 42, endTime: 55 },
  { title: "The Real Slim Shady", artist: "Eminem", videoId: "eJO5HU_7_1w", startTime: 48, endTime: 61 },
  { title: "Rap God", artist: "Eminem", videoId: "XbGs_qK2PQA", startTime: 54, endTime: 67 },
  { title: "Venom", artist: "Eminem", videoId: "8CdcCD5V-d8", startTime: 57, endTime: 70 },
  { title: "Godzilla", artist: "Eminem", videoId: "r_0JjYUe5jo", startTime: 60, endTime: 73 },
  { title: "Houdini", artist: "Eminem", videoId: "22tVWwmTie8", startTime: 63, endTime: 76 },
  { title: "Drowning", artist: "우즈", videoId: "tCTknBnBwrg", startTime: 48, endTime: 61 },
  { title: "Stronger", artist: "Kanye West", videoId: "PsO6ZnUZI0g", startTime: 42, endTime: 55 },
  { title: "Viva La Vida", artist: "Coldplay", videoId: "dvgZkm1xWPE", startTime: 45, endTime: 58 },
  { title: "A Sky Full of Stars", artist: "Coldplay", videoId: "VPRjCeoBqrI", startTime: 48, endTime: 61 },
  { title: "Believer", artist: "Imagine Dragons", videoId: "7wtfhZwyrcc", startTime: 51, endTime: 64 },
  { title: "Thunder", artist: "Imagine Dragons", videoId: "fKopy74weus", startTime: 54, endTime: 67 },
  { title: "Counting Stars", artist: "OneRepublic", videoId: "hT_nvWreIhg", startTime: 57, endTime: 70 },
  { title: "We Will Rock You", artist: "Queen", videoId: "-tJYN-eG1zk", startTime: 60, endTime: 73 },
  { title: "Don't Stop Me Now", artist: "Queen", videoId: "HgzGwKwLmgM", startTime: 63, endTime: 76 },
  { title: "Numb", artist: "Linkin Park", videoId: "kXYiU_JCYtU", startTime: 42, endTime: 55 },
  { title: "Wake Me Up", artist: "Avicii", videoId: "IcrbM1l_BoI", startTime: 45, endTime: 58 },
  { title: "Happy", artist: "Pharrell Williams", videoId: "ZbZSe6N_BXs", startTime: 48, endTime: 61 },
  { title: "Sharks", artist: "Imagine Dragons", videoId: "Te3_VlimRw0", startTime: 51, endTime: 64 },
  { title: "외톨이", artist: "아웃사이더", videoId: "N2rORO0B1j8", startTime: 54, endTime: 67 },
  { title: "곡예사", artist: "조광일", videoId: "aKuS6T2SZoI", startTime: 57, endTime: 70 },
];

if (SONGS_DB.length !== 200) {
  console.warn(`SONGS_DB length is ${SONGS_DB.length}. Expected 200.`);
}
